version: '3.8'
services:
  postgresql-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB.USERNAME}
      POSTGRES_PASSWORD: ${DB.PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    depends_on:
      - tomcat-10-1-10-jdk21
  tomcat-10-1-10-jdk21:
    image: tomcat:10.1.10-jdk21-openjdk
    ports:
      - "8888:8080"
      - "5005:5005"
    command: "catalina.sh run"
    volumes:
      - "./target/webapp:/usr/local/tomcat/webapps"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  nginx-frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./front:/usr/share/nginx/html"